name: moksha
favicon: null
layout_spectrum: 0.5986735087353736
typography_spectrum: 0.3840362310875207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6056446083821356
  lightness: 0.904615290928632
  saturation: 0.9621357778087258
  rhythmicContrast: 0.2114170012064278
purpose: []
